### ISSUE TITLE
class already exits error

### ISSUE THREAD

**Issue by lukereding** [gen2brain/dlgs#2]
I'm relatively new to Go, so I apologize in advance if this is something obvious.

I've written a Go program using `dlgs` which I've found super handy. The program calls `dlgs.Entry` twice, once right after the other. The program compiles and runs fine on OS X. On Windows, when the program hits the second `dlgs.Entry`, I get

```
panic: Class already exists.
```

Is this expected behavior or a bug?

**Comment by gen2brain** [comment]
Probably a bug, on Windows win32 api is used and window is created with class name "ClassEntry". I never programmed before with win32 api, so not sure what class name is supposed to do, and why it is there, but it probably complains because you have two opened windows with same class name. In win32 every component is actually a "window". 

Never saw that when I tested in Windows, but I never had two entries at the same time (that will probably also confuse user), ask for one entry, then ask for another is how I imagined this will be used.

**Comment by lukereding** [comment]
Thanks for the quick response!

>but I never had two entries at the same time (that will probably also confuse user), ask for one entry, then ask for another is how I imagined this will be used. 

I totally agree, and that's how it works when I run it on my Mac: it prompts the user for the first Entry, the user clicks OK, then the second Entry window pops up. 

What I'm trying to do now is

```
	varX, _, err := dlgs.Entry("ID", "Provide the ID: ", "NA")
	if err != nil {
		panic(err)
	}

	varY, _, err := dlgs.Entry("Your name", "Your name: ", "NA")
	if err != nil {
		panic(err)
	}
```
i.e. ask the user to input two things in succession. 

Is there a better way to ask the user for one entry, then ask for another?

**Comment by gen2brain** [comment]
That looks ok, the first one should just block and wait for response. I will need to find more info about classname and win32, and maybe just generate some random strings for that. I don't have access to Windows currently (I usually use it in vmware) so it will need some time.

**Comment by lukereding** [comment]
thanks for being so responsive

**Comment by gen2brain** [comment]
Fixed, it just needed UnregisterClass call.
